@startuml
'https://plantuml.com/class-diagram

interface CommandExecutor {
	void execute(Command command){}
}

class CutCommandExecutor implements CommandExecutor {
	- OptionExecutorFactory optionExecutorFactory;
	- PrinterFactory printerFactory;
	+ void execute(Command command)
}

class NonCutCommandExecutor implements CommandExecutor {
	- PrinterFactory printerFactory;
    + void execute(Command command)
}

class ExitCommandExecutor implements CommandExecutor {
	- PrinterFactory printerFactory;
	+ void execute(Command command)
}

CommandExecutor -- Command

!include Command.iuml!0


!include Factory.iuml!1
!include Factory.iuml!4
!include Factory.iuml!5

CommandExecutorFactory -- CommandExecutor

CutCommandExecutor -- OptionExecutorFactory



@enduml