@startuml
'https://plantuml.com/state-diagram

'scale 350 width
hide empty description

State Process {
    [*] --> Mode
    Mode --> Validation
    Validation --> Execution
    Execution --> [*]
}

State Mode {
    [*] --> Mode_Resolution
    Mode_Resolution --> Single_Command
    Mode_Resolution --> Piped_Command
}
@enduml